/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AdminRouteImport } from './routes/admin'
import { Route as ArchitectureRouteImport } from './routes/architecture'
import { Route as FarmerRouteImport } from './routes/farmer'
import { Route as LoginRouteImport } from './routes/login'
import { Route as OperatorRouteImport } from './routes/operator'
import { Route as RegisterRouteImport } from './routes/register'
import { Route as AdminIndexRouteImport } from './routes/admin.index'
import { Route as AdminAlertsRouteImport } from './routes/admin.alerts'
import { Route as AdminAnalyticsRouteImport } from './routes/admin.analytics'
import { Route as AdminCentresRouteImport } from './routes/admin.centres'
import { Route as FarmerIndexRouteImport } from './routes/farmer.index'
import { Route as FarmerBookRouteImport } from './routes/farmer.book'
import { Route as FarmerCentresRouteImport } from './routes/farmer.centres'
import { Route as FarmerGrievancesRouteImport } from './routes/farmer.grievances'
import { Route as FarmerHistoryRouteImport } from './routes/farmer.history'
import { Route as FarmerNotificationsRouteImport } from './routes/farmer.notifications'
import { Route as FarmerPaymentsRouteImport } from './routes/farmer.payments'
import { Route as FarmerProcurementRouteImport } from './routes/farmer.procurement'
import { Route as FarmerProfileRouteImport } from './routes/farmer.profile'
import { Route as FarmerQueueRouteImport } from './routes/farmer.queue'
import { Route as OperatorIndexRouteImport } from './routes/operator.index'
import { Route as OperatorAnalyticsRouteImport } from './routes/operator.analytics'
import { Route as OperatorAppointmentsRouteImport } from './routes/operator.appointments'
import { Route as OperatorNotificationsRouteImport } from './routes/operator.notifications'
import { Route as OperatorPaymentsRouteImport } from './routes/operator.payments'
import { Route as OperatorProcurementRouteImport } from './routes/operator.procurement'
import { Route as OperatorQueueRouteImport } from './routes/operator.queue'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const ArchitectureRoute = ArchitectureRouteImport.update({
  id: '/architecture',
  path: '/architecture',
  getParentRoute: () => rootRouteImport,
} as any)
const FarmerRoute = FarmerRouteImport.update({
  id: '/farmer',
  path: '/farmer',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const OperatorRoute = OperatorRouteImport.update({
  id: '/operator',
  path: '/operator',
  getParentRoute: () => rootRouteImport,
} as any)
const RegisterRoute = RegisterRouteImport.update({
  id: '/register',
  path: '/register',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminIndexRoute = AdminIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AdminRoute,
} as any)
const AdminAlertsRoute = AdminAlertsRouteImport.update({
  id: '/alerts',
  path: '/alerts',
  getParentRoute: () => AdminRoute,
} as any)
const AdminAnalyticsRoute = AdminAnalyticsRouteImport.update({
  id: '/analytics',
  path: '/analytics',
  getParentRoute: () => AdminRoute,
} as any)
const AdminCentresRoute = AdminCentresRouteImport.update({
  id: '/centres',
  path: '/centres',
  getParentRoute: () => AdminRoute,
} as any)
const FarmerIndexRoute = FarmerIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => FarmerRoute,
} as any)
const FarmerBookRoute = FarmerBookRouteImport.update({
  id: '/book',
  path: '/book',
  getParentRoute: () => FarmerRoute,
} as any)
const FarmerCentresRoute = FarmerCentresRouteImport.update({
  id: '/centres',
  path: '/centres',
  getParentRoute: () => FarmerRoute,
} as any)
const FarmerGrievancesRoute = FarmerGrievancesRouteImport.update({
  id: '/grievances',
  path: '/grievances',
  getParentRoute: () => FarmerRoute,
} as any)
const FarmerHistoryRoute = FarmerHistoryRouteImport.update({
  id: '/history',
  path: '/history',
  getParentRoute: () => FarmerRoute,
} as any)
const FarmerNotificationsRoute = FarmerNotificationsRouteImport.update({
  id: '/notifications',
  path: '/notifications',
  getParentRoute: () => FarmerRoute,
} as any)
const FarmerPaymentsRoute = FarmerPaymentsRouteImport.update({
  id: '/payments',
  path: '/payments',
  getParentRoute: () => FarmerRoute,
} as any)
const FarmerProcurementRoute = FarmerProcurementRouteImport.update({
  id: '/procurement',
  path: '/procurement',
  getParentRoute: () => FarmerRoute,
} as any)
const FarmerProfileRoute = FarmerProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => FarmerRoute,
} as any)
const FarmerQueueRoute = FarmerQueueRouteImport.update({
  id: '/queue',
  path: '/queue',
  getParentRoute: () => FarmerRoute,
} as any)
const OperatorIndexRoute = OperatorIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => OperatorRoute,
} as any)
const OperatorAnalyticsRoute = OperatorAnalyticsRouteImport.update({
  id: '/analytics',
  path: '/analytics',
  getParentRoute: () => OperatorRoute,
} as any)
const OperatorAppointmentsRoute = OperatorAppointmentsRouteImport.update({
  id: '/appointments',
  path: '/appointments',
  getParentRoute: () => OperatorRoute,
} as any)
const OperatorNotificationsRoute = OperatorNotificationsRouteImport.update({
  id: '/notifications',
  path: '/notifications',
  getParentRoute: () => OperatorRoute,
} as any)
const OperatorPaymentsRoute = OperatorPaymentsRouteImport.update({
  id: '/payments',
  path: '/payments',
  getParentRoute: () => OperatorRoute,
} as any)
const OperatorProcurementRoute = OperatorProcurementRouteImport.update({
  id: '/procurement',
  path: '/procurement',
  getParentRoute: () => OperatorRoute,
} as any)
const OperatorQueueRoute = OperatorQueueRouteImport.update({
  id: '/queue',
  path: '/queue',
  getParentRoute: () => OperatorRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/admin': typeof AdminRouteWithChildren
  '/architecture': typeof ArchitectureRoute
  '/farmer': typeof FarmerRouteWithChildren
  '/login': typeof LoginRoute
  '/operator': typeof OperatorRouteWithChildren
  '/register': typeof RegisterRoute
  '/admin/alerts': typeof AdminAlertsRoute
  '/admin/analytics': typeof AdminAnalyticsRoute
  '/admin/centres': typeof AdminCentresRoute
  '/farmer/book': typeof FarmerBookRoute
  '/farmer/centres': typeof FarmerCentresRoute
  '/farmer/grievances': typeof FarmerGrievancesRoute
  '/farmer/history': typeof FarmerHistoryRoute
  '/farmer/notifications': typeof FarmerNotificationsRoute
  '/farmer/payments': typeof FarmerPaymentsRoute
  '/farmer/procurement': typeof FarmerProcurementRoute
  '/farmer/profile': typeof FarmerProfileRoute
  '/farmer/queue': typeof FarmerQueueRoute
  '/operator/analytics': typeof OperatorAnalyticsRoute
  '/operator/appointments': typeof OperatorAppointmentsRoute
  '/operator/notifications': typeof OperatorNotificationsRoute
  '/operator/payments': typeof OperatorPaymentsRoute
  '/operator/procurement': typeof OperatorProcurementRoute
  '/operator/queue': typeof OperatorQueueRoute
  '/admin/': typeof AdminIndexRoute
  '/farmer/': typeof FarmerIndexRoute
  '/operator/': typeof OperatorIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/architecture': typeof ArchitectureRoute
  '/login': typeof LoginRoute
  '/register': typeof RegisterRoute
  '/admin/alerts': typeof AdminAlertsRoute
  '/admin/analytics': typeof AdminAnalyticsRoute
  '/admin/centres': typeof AdminCentresRoute
  '/farmer/book': typeof FarmerBookRoute
  '/farmer/centres': typeof FarmerCentresRoute
  '/farmer/grievances': typeof FarmerGrievancesRoute
  '/farmer/history': typeof FarmerHistoryRoute
  '/farmer/notifications': typeof FarmerNotificationsRoute
  '/farmer/payments': typeof FarmerPaymentsRoute
  '/farmer/procurement': typeof FarmerProcurementRoute
  '/farmer/profile': typeof FarmerProfileRoute
  '/farmer/queue': typeof FarmerQueueRoute
  '/operator/analytics': typeof OperatorAnalyticsRoute
  '/operator/appointments': typeof OperatorAppointmentsRoute
  '/operator/notifications': typeof OperatorNotificationsRoute
  '/operator/payments': typeof OperatorPaymentsRoute
  '/operator/procurement': typeof OperatorProcurementRoute
  '/operator/queue': typeof OperatorQueueRoute
  '/admin': typeof AdminIndexRoute
  '/farmer': typeof FarmerIndexRoute
  '/operator': typeof OperatorIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/admin': typeof AdminRouteWithChildren
  '/architecture': typeof ArchitectureRoute
  '/farmer': typeof FarmerRouteWithChildren
  '/login': typeof LoginRoute
  '/operator': typeof OperatorRouteWithChildren
  '/register': typeof RegisterRoute
  '/admin/alerts': typeof AdminAlertsRoute
  '/admin/analytics': typeof AdminAnalyticsRoute
  '/admin/centres': typeof AdminCentresRoute
  '/farmer/book': typeof FarmerBookRoute
  '/farmer/centres': typeof FarmerCentresRoute
  '/farmer/grievances': typeof FarmerGrievancesRoute
  '/farmer/history': typeof FarmerHistoryRoute
  '/farmer/notifications': typeof FarmerNotificationsRoute
  '/farmer/payments': typeof FarmerPaymentsRoute
  '/farmer/procurement': typeof FarmerProcurementRoute
  '/farmer/profile': typeof FarmerProfileRoute
  '/farmer/queue': typeof FarmerQueueRoute
  '/operator/analytics': typeof OperatorAnalyticsRoute
  '/operator/appointments': typeof OperatorAppointmentsRoute
  '/operator/notifications': typeof OperatorNotificationsRoute
  '/operator/payments': typeof OperatorPaymentsRoute
  '/operator/procurement': typeof OperatorProcurementRoute
  '/operator/queue': typeof OperatorQueueRoute
  '/admin/': typeof AdminIndexRoute
  '/farmer/': typeof FarmerIndexRoute
  '/operator/': typeof OperatorIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/admin'
    | '/architecture'
    | '/farmer'
    | '/login'
    | '/operator'
    | '/register'
    | '/admin/alerts'
    | '/admin/analytics'
    | '/admin/centres'
    | '/farmer/book'
    | '/farmer/centres'
    | '/farmer/grievances'
    | '/farmer/history'
    | '/farmer/notifications'
    | '/farmer/payments'
    | '/farmer/procurement'
    | '/farmer/profile'
    | '/farmer/queue'
    | '/operator/analytics'
    | '/operator/appointments'
    | '/operator/notifications'
    | '/operator/payments'
    | '/operator/procurement'
    | '/operator/queue'
    | '/admin/'
    | '/farmer/'
    | '/operator/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/architecture'
    | '/login'
    | '/register'
    | '/admin/alerts'
    | '/admin/analytics'
    | '/admin/centres'
    | '/farmer/book'
    | '/farmer/centres'
    | '/farmer/grievances'
    | '/farmer/history'
    | '/farmer/notifications'
    | '/farmer/payments'
    | '/farmer/procurement'
    | '/farmer/profile'
    | '/farmer/queue'
    | '/operator/analytics'
    | '/operator/appointments'
    | '/operator/notifications'
    | '/operator/payments'
    | '/operator/procurement'
    | '/operator/queue'
    | '/admin'
    | '/farmer'
    | '/operator'
  id:
    | '__root__'
    | '/'
    | '/admin'
    | '/architecture'
    | '/farmer'
    | '/login'
    | '/operator'
    | '/register'
    | '/admin/alerts'
    | '/admin/analytics'
    | '/admin/centres'
    | '/farmer/book'
    | '/farmer/centres'
    | '/farmer/grievances'
    | '/farmer/history'
    | '/farmer/notifications'
    | '/farmer/payments'
    | '/farmer/procurement'
    | '/farmer/profile'
    | '/farmer/queue'
    | '/operator/analytics'
    | '/operator/appointments'
    | '/operator/notifications'
    | '/operator/payments'
    | '/operator/procurement'
    | '/operator/queue'
    | '/admin/'
    | '/farmer/'
    | '/operator/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AdminRoute: typeof AdminRouteWithChildren
  ArchitectureRoute: typeof ArchitectureRoute
  FarmerRoute: typeof FarmerRouteWithChildren
  LoginRoute: typeof LoginRoute
  OperatorRoute: typeof OperatorRouteWithChildren
  RegisterRoute: typeof RegisterRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/architecture': {
      id: '/architecture'
      path: '/architecture'
      fullPath: '/architecture'
      preLoaderRoute: typeof ArchitectureRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/farmer': {
      id: '/farmer'
      path: '/farmer'
      fullPath: '/farmer'
      preLoaderRoute: typeof FarmerRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/operator': {
      id: '/operator'
      path: '/operator'
      fullPath: '/operator'
      preLoaderRoute: typeof OperatorRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/register': {
      id: '/register'
      path: '/register'
      fullPath: '/register'
      preLoaderRoute: typeof RegisterRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/': {
      id: '/admin/'
      path: '/'
      fullPath: '/admin/'
      preLoaderRoute: typeof AdminIndexRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/alerts': {
      id: '/admin/alerts'
      path: '/alerts'
      fullPath: '/admin/alerts'
      preLoaderRoute: typeof AdminAlertsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/analytics': {
      id: '/admin/analytics'
      path: '/analytics'
      fullPath: '/admin/analytics'
      preLoaderRoute: typeof AdminAnalyticsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/centres': {
      id: '/admin/centres'
      path: '/centres'
      fullPath: '/admin/centres'
      preLoaderRoute: typeof AdminCentresRouteImport
      parentRoute: typeof AdminRoute
    }
    '/farmer/': {
      id: '/farmer/'
      path: '/'
      fullPath: '/farmer/'
      preLoaderRoute: typeof FarmerIndexRouteImport
      parentRoute: typeof FarmerRoute
    }
    '/farmer/book': {
      id: '/farmer/book'
      path: '/book'
      fullPath: '/farmer/book'
      preLoaderRoute: typeof FarmerBookRouteImport
      parentRoute: typeof FarmerRoute
    }
    '/farmer/centres': {
      id: '/farmer/centres'
      path: '/centres'
      fullPath: '/farmer/centres'
      preLoaderRoute: typeof FarmerCentresRouteImport
      parentRoute: typeof FarmerRoute
    }
    '/farmer/grievances': {
      id: '/farmer/grievances'
      path: '/grievances'
      fullPath: '/farmer/grievances'
      preLoaderRoute: typeof FarmerGrievancesRouteImport
      parentRoute: typeof FarmerRoute
    }
    '/farmer/history': {
      id: '/farmer/history'
      path: '/history'
      fullPath: '/farmer/history'
      preLoaderRoute: typeof FarmerHistoryRouteImport
      parentRoute: typeof FarmerRoute
    }
    '/farmer/notifications': {
      id: '/farmer/notifications'
      path: '/notifications'
      fullPath: '/farmer/notifications'
      preLoaderRoute: typeof FarmerNotificationsRouteImport
      parentRoute: typeof FarmerRoute
    }
    '/farmer/payments': {
      id: '/farmer/payments'
      path: '/payments'
      fullPath: '/farmer/payments'
      preLoaderRoute: typeof FarmerPaymentsRouteImport
      parentRoute: typeof FarmerRoute
    }
    '/farmer/procurement': {
      id: '/farmer/procurement'
      path: '/procurement'
      fullPath: '/farmer/procurement'
      preLoaderRoute: typeof FarmerProcurementRouteImport
      parentRoute: typeof FarmerRoute
    }
    '/farmer/profile': {
      id: '/farmer/profile'
      path: '/profile'
      fullPath: '/farmer/profile'
      preLoaderRoute: typeof FarmerProfileRouteImport
      parentRoute: typeof FarmerRoute
    }
    '/farmer/queue': {
      id: '/farmer/queue'
      path: '/queue'
      fullPath: '/farmer/queue'
      preLoaderRoute: typeof FarmerQueueRouteImport
      parentRoute: typeof FarmerRoute
    }
    '/operator/': {
      id: '/operator/'
      path: '/'
      fullPath: '/operator/'
      preLoaderRoute: typeof OperatorIndexRouteImport
      parentRoute: typeof OperatorRoute
    }
    '/operator/analytics': {
      id: '/operator/analytics'
      path: '/analytics'
      fullPath: '/operator/analytics'
      preLoaderRoute: typeof OperatorAnalyticsRouteImport
      parentRoute: typeof OperatorRoute
    }
    '/operator/appointments': {
      id: '/operator/appointments'
      path: '/appointments'
      fullPath: '/operator/appointments'
      preLoaderRoute: typeof OperatorAppointmentsRouteImport
      parentRoute: typeof OperatorRoute
    }
    '/operator/notifications': {
      id: '/operator/notifications'
      path: '/notifications'
      fullPath: '/operator/notifications'
      preLoaderRoute: typeof OperatorNotificationsRouteImport
      parentRoute: typeof OperatorRoute
    }
    '/operator/payments': {
      id: '/operator/payments'
      path: '/payments'
      fullPath: '/operator/payments'
      preLoaderRoute: typeof OperatorPaymentsRouteImport
      parentRoute: typeof OperatorRoute
    }
    '/operator/procurement': {
      id: '/operator/procurement'
      path: '/procurement'
      fullPath: '/operator/procurement'
      preLoaderRoute: typeof OperatorProcurementRouteImport
      parentRoute: typeof OperatorRoute
    }
    '/operator/queue': {
      id: '/operator/queue'
      path: '/queue'
      fullPath: '/operator/queue'
      preLoaderRoute: typeof OperatorQueueRouteImport
      parentRoute: typeof OperatorRoute
    }
  }
}

interface AdminRouteChildren {
  AdminAlertsRoute: typeof AdminAlertsRoute
  AdminAnalyticsRoute: typeof AdminAnalyticsRoute
  AdminCentresRoute: typeof AdminCentresRoute
  AdminIndexRoute: typeof AdminIndexRoute
}

const AdminRouteChildren: AdminRouteChildren = {
  AdminAlertsRoute: AdminAlertsRoute,
  AdminAnalyticsRoute: AdminAnalyticsRoute,
  AdminCentresRoute: AdminCentresRoute,
  AdminIndexRoute: AdminIndexRoute,
}

const AdminRouteWithChildren = AdminRoute._addFileChildren(AdminRouteChildren)

interface FarmerRouteChildren {
  FarmerBookRoute: typeof FarmerBookRoute
  FarmerCentresRoute: typeof FarmerCentresRoute
  FarmerGrievancesRoute: typeof FarmerGrievancesRoute
  FarmerHistoryRoute: typeof FarmerHistoryRoute
  FarmerNotificationsRoute: typeof FarmerNotificationsRoute
  FarmerPaymentsRoute: typeof FarmerPaymentsRoute
  FarmerProcurementRoute: typeof FarmerProcurementRoute
  FarmerProfileRoute: typeof FarmerProfileRoute
  FarmerQueueRoute: typeof FarmerQueueRoute
  FarmerIndexRoute: typeof FarmerIndexRoute
}

const FarmerRouteChildren: FarmerRouteChildren = {
  FarmerBookRoute: FarmerBookRoute,
  FarmerCentresRoute: FarmerCentresRoute,
  FarmerGrievancesRoute: FarmerGrievancesRoute,
  FarmerHistoryRoute: FarmerHistoryRoute,
  FarmerNotificationsRoute: FarmerNotificationsRoute,
  FarmerPaymentsRoute: FarmerPaymentsRoute,
  FarmerProcurementRoute: FarmerProcurementRoute,
  FarmerProfileRoute: FarmerProfileRoute,
  FarmerQueueRoute: FarmerQueueRoute,
  FarmerIndexRoute: FarmerIndexRoute,
}

const FarmerRouteWithChildren =
  FarmerRoute._addFileChildren(FarmerRouteChildren)

interface OperatorRouteChildren {
  OperatorAnalyticsRoute: typeof OperatorAnalyticsRoute
  OperatorAppointmentsRoute: typeof OperatorAppointmentsRoute
  OperatorNotificationsRoute: typeof OperatorNotificationsRoute
  OperatorPaymentsRoute: typeof OperatorPaymentsRoute
  OperatorProcurementRoute: typeof OperatorProcurementRoute
  OperatorQueueRoute: typeof OperatorQueueRoute
  OperatorIndexRoute: typeof OperatorIndexRoute
}

const OperatorRouteChildren: OperatorRouteChildren = {
  OperatorAnalyticsRoute: OperatorAnalyticsRoute,
  OperatorAppointmentsRoute: OperatorAppointmentsRoute,
  OperatorNotificationsRoute: OperatorNotificationsRoute,
  OperatorPaymentsRoute: OperatorPaymentsRoute,
  OperatorProcurementRoute: OperatorProcurementRoute,
  OperatorQueueRoute: OperatorQueueRoute,
  OperatorIndexRoute: OperatorIndexRoute,
}

const OperatorRouteWithChildren = OperatorRoute._addFileChildren(
  OperatorRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AdminRoute: AdminRouteWithChildren,
  ArchitectureRoute: ArchitectureRoute,
  FarmerRoute: FarmerRouteWithChildren,
  LoginRoute: LoginRoute,
  OperatorRoute: OperatorRouteWithChildren,
  RegisterRoute: RegisterRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
